baseURL: 'http://blog.jread.com/'
languageCode: 'en-gb'
author: "James Read"
copyright: "James Read"
title: "James Read's Code, Containers & Cloud blog"
theme: 'jwr'

outputs:
  home:
    - html
    - rss
  section:
    - html
    - rss
  taxonomy:
    - html
  term:
    - html

params:
  favicon: logo.png
  logo: "logo.png"
  author: "James Read"
  githubuser: "jamesread"
  description: "James Read's Code, Containers & Cloud blog"
  useFeaturedImage: false

menu:
  main:
    - name: 'Home'
      pageRef: '/'
      weight: 1

    - name: 'Code'
      pageRef: '/tags/code'
      weight: 2

    - name: 'Containers'
      pageRef: '/tags/containers'
      weight: 3

    - name: 'Cloud'
      pageRef: '/tags/cloud'
      weight: 4

    - name: 'All Tags'
      pageRef: '/tags/'
      weight: 5

    - name: "James' Homepage"
      pageRef: 'http://jread.com'
      weight: 6
      params:
        class: last

markup:
  goldmark:
    renderer:
      unsafe: true
